stages:
  - build
  - QA
  - test

variables:
  GIT_STRATEGY: fetch
  FWD_COMPOSE_EXEC_FLAGS: -T

include:
  - https://ci.fwd.tools/gitlab/v1.0/vendor.yml
  # - https://ci.fwd.tools/gitlab/v1.0/vendor-with-private.yml
  - https://ci.fwd.tools/gitlab/v1.0/assets.yml
  - https://ci.fwd.tools/gitlab/v1.0/eslint.yml
  - https://ci.fwd.tools/gitlab/v1.0/phpmnd.yml
  - https://ci.fwd.tools/gitlab/v1.0/phpcpd.yml
  - https://ci.fwd.tools/gitlab/v1.0/php-cs-fixer.yml
  - https://ci.fwd.tools/gitlab/v1.0/phan.yml
  - https://ci.fwd.tools/gitlab/v1.0/phpmd.yml
  - https://ci.fwd.tools/gitlab/v1.0/security-check.yml
  - https://ci.fwd.tools/gitlab/v1.0/dusk.yml
  - https://ci.fwd.tools/gitlab/v1.0/phpunit.yml

# build
vendor:
  extends: .vendor

# vendor:
#   extends: .vendor-with-private
#   variables:
#     CUSTOM_HOST: gitlab.example.com

assets:
  extends: .assets
# build

# QA
eslint:
  extends: .eslint

php-cs-fixer:
  extends: .php-cs-fixer

phpmd:
  extends: .phpmd

security-check:
  extends: .security-check

phpmnd:
  extends: .phpmnd

phpcpd:
  extends: .phpcpd

phan:
  extends: .phan
# QA

# test
dusk:
  extends: .dusk

phpunit:
  extends: .phpunit
# test
